// Code generated by internal/cmd/genmanifest. DO NOT EDIT.

package eventsub

func newDefaultRegistry() Registry {
	registry := NewRegistry()
	registry.Register("channel.follow", "2", decodeInto[ChannelFollowEvent])
	registry.Register("stream.online", "1", decodeInto[StreamOnlineEvent])
	return registry
}
