package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

type manifest struct {
	Events []eventDef `json:"events"`
}

type eventDef struct {
	SubscriptionType string `json:"subscription_type"`
	Version          string `json:"version"`
	GoType           string `json:"go_type"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "genmanifest: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	wd, err := os.Getwd()
	if err != nil {
		return err
	}

	root, err := findRepoRoot(wd)
	if err != nil {
		return err
	}

	manifestPath := filepath.Join(root, "internal", "manifest", "eventsub.json")
	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		return err
	}

	var data manifest
	if err := json.Unmarshal(raw, &data); err != nil {
		return err
	}

	var out bytes.Buffer
	if err := generatedRegistryTmpl.Execute(&out, data); err != nil {
		return err
	}

	outputPath := filepath.Join(root, "eventsub", "generated_registry.go")
	return os.WriteFile(outputPath, out.Bytes(), 0o644)
}

func findRepoRoot(start string) (string, error) {
	dir := start

	for {
		manifestPath := filepath.Join(dir, "internal", "manifest", "eventsub.json")
		_, err := os.Stat(manifestPath)
		switch {
		case err == nil:
			return dir, nil
		case !errors.Is(err, os.ErrNotExist):
			return "", err
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repository root from %q", start)
		}

		dir = parent
	}
}

var generatedRegistryTmpl = template.Must(template.New("registry").Parse(`// Code generated by internal/cmd/genmanifest. DO NOT EDIT.

package eventsub

func newDefaultRegistry() Registry {
	registry := NewRegistry()
{{- range .Events }}
	registry.Register({{ printf "%q" .SubscriptionType }}, {{ printf "%q" .Version }}, decodeInto[{{ .GoType }}])
{{- end }}
	return registry
}
`))
