package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type manifest struct {
	Events []eventDef `json:"events"`
}

type eventDef struct {
	SubscriptionType string `json:"subscription_type"`
	Version          string `json:"version"`
	GoType           string `json:"go_type"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "genmanifest: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	wd, err := os.Getwd()
	if err != nil {
		return err
	}

	root, err := findRepoRoot(wd)
	if err != nil {
		return err
	}

	manifestPath := filepath.Join(root, "internal", "manifest", "eventsub.json")
	data, err := loadManifest(manifestPath)
	if err != nil {
		return err
	}

	out, err := renderRegistry(data)
	if err != nil {
		return err
	}

	outputPath := filepath.Join(root, "eventsub", "generated_registry.go")
	return os.WriteFile(outputPath, out, 0o644)
}

func loadManifest(path string) (manifest, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return manifest{}, err
	}

	var data manifest
	if err := json.Unmarshal(raw, &data); err != nil {
		return manifest{}, err
	}
	if err := validateManifest(data); err != nil {
		return manifest{}, err
	}
	return data, nil
}

func validateManifest(data manifest) error {
	seen := map[string]struct{}{}
	for i, event := range data.Events {
		if strings.TrimSpace(event.SubscriptionType) == "" {
			return fmt.Errorf("events[%d]: subscription_type is required", i)
		}
		if strings.TrimSpace(event.Version) == "" {
			return fmt.Errorf("events[%d]: version is required", i)
		}
		if strings.TrimSpace(event.GoType) == "" {
			return fmt.Errorf("events[%d]: go_type is required", i)
		}
		key := event.SubscriptionType + "@" + event.Version
		if _, ok := seen[key]; ok {
			return fmt.Errorf("events[%d]: duplicate event %q", i, key)
		}
		seen[key] = struct{}{}
	}
	return nil
}

func renderRegistry(data manifest) ([]byte, error) {
	var out bytes.Buffer
	if err := generatedRegistryTmpl.Execute(&out, data); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

func findRepoRoot(start string) (string, error) {
	dir := start

	for {
		manifestPath := filepath.Join(dir, "internal", "manifest", "eventsub.json")
		_, err := os.Stat(manifestPath)
		switch {
		case err == nil:
			return dir, nil
		case !errors.Is(err, os.ErrNotExist):
			return "", err
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repository root from %q", start)
		}

		dir = parent
	}
}

var generatedRegistryTmpl = template.Must(template.New("registry").Parse(`// Code generated by internal/cmd/genmanifest. DO NOT EDIT.

package eventsub

func newDefaultRegistry() Registry {
	registry := NewRegistry()
{{- range .Events }}
	registry.Register({{ printf "%q" .SubscriptionType }}, {{ printf "%q" .Version }}, decodeInto[{{ .GoType }}])
{{- end }}
	return registry
}
`))
